version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Build step"
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
  discard-paths: yes
